version: '3.8'

services:
  flask_app:
    git_url: https://github.com/your-username/your-flask-repo.git
    git_branch: main
    dockerfile_path: ./Dockerfile
    build_root: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - EMAIL_SENDER=your_email@gmail.com
      - EMAIL_PASSWORD=your_email_password
      - EMAIL_RECEIVER=recipient_email@example.com
    volumes:
      - ./app:/app
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
